import type { Permission } from "../src/lib/domain";

// Role catalogue per spec Section 21. Permissions are "resource:action:level".
// Level is the maximum data scope the role grants for that resource.

const groupRead: Permission[] = [
  "task:read:group",
  "project:read:group",
  "kpi:read:group",
  "decision:read:group",
  "risk:read:group",
  "document:read:group",
  "knowledge:read:group",
  "meeting:read:group",
  "announcement:read:group",
  "approval:read:group",
  "people:read:group",
  "subsidiary:read:group",
  "department:read:group",
  "finance:read:group",
  "strategy:read:group",
  "search:read:group",
  "workflow:read:group",
  "incident:read:group",
  "opportunity:read:group",
  "issue:read:group",
  "message:read:group",
  "notification:read:own",
];

const groupWrite: Permission[] = [
  "task:create:group",
  "task:update:group",
  "project:create:group",
  "project:update:group",
  "kpi:create:group",
  "kpi:update:group",
  "decision:create:group",
  "decision:update:group",
  "decision:approve:group",
  "risk:create:group",
  "risk:update:group",
  "document:create:group",
  "document:update:group",
  "knowledge:create:group",
  "meeting:create:group",
  "meeting:update:group",
  "announcement:create:group",
  "approval:create:group",
  "approval:approve:group",
  "finance:update:group",
  "strategy:create:group",
  "strategy:update:group",
  "ai:read:group",
  "incident:create:group",
  "incident:update:group",
  "opportunity:create:group",
  "opportunity:update:group",
  "issue:create:group",
  "issue:update:group",
  "message:create:group",
  "message:update:own",
  "workflow:create:group",
  "workflow:update:group",
  "document:approve:group",
];

const subsidiaryScope: Permission[] = [
  "task:read:subsidiary",
  "project:read:subsidiary",
  "kpi:read:subsidiary",
  "decision:read:subsidiary",
  "risk:read:subsidiary",
  "document:read:subsidiary",
  "knowledge:read:subsidiary",
  "meeting:read:subsidiary",
  "announcement:read:subsidiary",
  "approval:read:subsidiary",
  "people:read:subsidiary",
  "subsidiary:read:subsidiary",
  "department:read:subsidiary",
  "finance:read:subsidiary",
  "strategy:read:subsidiary",
  "search:read:subsidiary",
  "incident:read:subsidiary",
  "opportunity:read:subsidiary",
  "issue:read:subsidiary",
  "message:read:subsidiary",
  "notification:read:own",
  "ai:read:subsidiary",
];

const subsidiaryWrite: Permission[] = [
  "task:create:subsidiary",
  "task:update:subsidiary",
  "project:create:subsidiary",
  "project:update:subsidiary",
  "kpi:create:subsidiary",
  "kpi:update:subsidiary",
  "decision:create:subsidiary",
  "decision:update:subsidiary",
  "decision:approve:subsidiary",
  "risk:create:subsidiary",
  "risk:update:subsidiary",
  "document:create:subsidiary",
  "document:update:subsidiary",
  "knowledge:create:subsidiary",
  "meeting:create:subsidiary",
  "announcement:create:subsidiary",
  "approval:create:subsidiary",
  "approval:approve:subsidiary",
  "opportunity:create:subsidiary",
  "opportunity:update:subsidiary",
  "issue:create:subsidiary",
  "issue:update:subsidiary",
  "message:create:subsidiary",
  "workflow:read:subsidiary",
  "document:approve:subsidiary",
];

const departmentScope: Permission[] = [
  "task:read:department",
  "project:read:department",
  "kpi:read:department",
  "decision:read:department",
  "risk:read:department",
  "document:read:department",
  "knowledge:read:department",
  "meeting:read:department",
  "announcement:read:group",
  "approval:read:department",
  "people:read:department",
  "department:read:department",
  "strategy:read:department",
  "search:read:department",
  "issue:read:department",
  "message:read:department",
  "notification:read:own",
  "ai:read:department",
];

const departmentWrite: Permission[] = [
  "task:create:department",
  "task:update:department",
  "task:approve:department",
  "project:create:department",
  "project:update:department",
  "kpi:create:department",
  "kpi:update:department",
  "decision:create:department",
  "risk:create:department",
  "risk:update:department",
  "document:create:department",
  "document:update:department",
  "knowledge:create:department",
  "meeting:create:department",
  "approval:create:department",
  "approval:approve:department",
  "issue:create:department",
  "issue:update:department",
  "message:create:department",
];

const employeeScope: Permission[] = [
  "task:read:own",
  "project:read:own",
  "kpi:read:department",
  "decision:read:department",
  "document:read:department",
  "knowledge:read:group",
  "meeting:read:department",
  "announcement:read:group",
  "approval:read:own",
  "people:read:department",
  "search:read:own",
  "message:read:department",
  "notification:read:own",
  "ai:read:own",
  "issue:create:own",
  "opportunity:create:own",
];

const employeeWrite: Permission[] = [
  "task:create:own",
  "task:update:own",
  "document:create:own",
  "knowledge:create:own",
  "meeting:create:department",
  "approval:create:own",
  "message:create:department",
  "issue:create:own",
  "opportunity:create:own",
];

export type RoleDef = {
  code: string;
  name: string;
  level: "group" | "subsidiary" | "department" | "system";
  description: string;
  permissions: Permission[];
  isSystem?: boolean;
};

export const ROLE_DEFS: RoleDef[] = [
  {
    code: "GROUP_CEO",
    name: "Group CEO",
    level: "group",
    description:
      "Founder & Group CEO. Full institutional visibility across strategy, capital, risk, subsidiaries and governance.",
    permissions: [...groupRead, ...groupWrite, "subsidiary:create:group", "department:create:group"],
  },
  {
    code: "GROUP_EXECUTIVE",
    name: "Group Executive",
    level: "group",
    description: "Authorised C-Suite executive with group-wide read and executive write scope.",
    permissions: [...groupRead, ...groupWrite],
  },
  {
    code: "BOARD_MEMBER",
    name: "Board Member",
    level: "group",
    description:
      "Governance visibility: read across strategy, risk, finance, decisions and audit; no operational write.",
    permissions: [
      ...groupRead,
      "decision:approve:group",
      "risk:update:group",
      "document:read:group",
      "audit:read:group",
      "ai:read:group",
    ],
  },
  {
    code: "GROUP_CFO",
    name: "Group CFO",
    level: "group",
    description: "Financial stewardship: group finance read/write, capital approvals, budget oversight.",
    permissions: [
      ...groupRead,
      ...groupWrite,
      "finance:update:group",
      "approval:approve:group",
      "kpi:create:group",
      "kpi:update:group",
    ],
  },
  {
    code: "GROUP_COO",
    name: "Group COO",
    level: "group",
    description: "Operational command across subsidiaries, projects and execution.",
    permissions: [...groupRead, ...groupWrite, "incident:create:group", "incident:update:group"],
  },
  {
    code: "GROUP_CIO",
    name: "Group CIO/CTO",
    level: "group",
    description: "Technology and security command: systems, incidents, AI governance.",
    permissions: [
      ...groupRead,
      ...groupWrite,
      "incident:create:group",
      "incident:update:group",
      "admin:update:group",
      "audit:read:group",
      "ai:read:group",
    ],
  },
  {
    code: "GROUP_CHRO",
    name: "Group CHRO",
    level: "group",
    description: "People command: directory, performance, learning and organisational health.",
    permissions: [...groupRead, ...groupWrite, "people:update:group", "kpi:create:group"],
  },
  {
    code: "GROUP_GENERAL_COUNSEL",
    name: "Group General Counsel",
    level: "group",
    description: "Legal command: contracts, compliance obligations, legal risk, decisions.",
    permissions: [
      ...groupRead,
      ...groupWrite,
      "document:approve:group",
      "risk:update:group",
      "decision:approve:group",
    ],
  },
  {
    code: "GROUP_RISK_OFFICER",
    name: "Group Risk Officer",
    level: "group",
    description: "Risk command: group risk register, heatmaps, escalation and acceptance.",
    permissions: [
      ...groupRead,
      "risk:create:group",
      "risk:update:group",
      "risk:approve:group",
      "incident:create:group",
      "incident:update:group",
      "decision:read:group",
      "ai:read:group",
      "approval:approve:group",
    ],
  },
  {
    code: "GROUP_COMPLIANCE_OFFICER",
    name: "Group Compliance Officer",
    level: "group",
    description: "Compliance command: controls, obligations, audit trails, policy approvals.",
    permissions: [
      ...groupRead,
      "risk:read:group",
      "risk:update:group",
      "document:read:group",
      "document:approve:group",
      "audit:read:group",
      "decision:read:group",
      "ai:read:group",
      "approval:approve:group",
    ],
  },
  {
    code: "SUBSIDIARY_CEO",
    name: "Subsidiary CEO",
    level: "subsidiary",
    description:
      "Runs one subsidiary's operating environment while retaining appropriate AGH visibility.",
    permissions: [...subsidiaryScope, ...subsidiaryWrite, "department:create:subsidiary"],
  },
  {
    code: "MANAGING_DIRECTOR",
    name: "Managing Director",
    level: "subsidiary",
    description: "Managing Director of a business unit or regional operation.",
    permissions: [...subsidiaryScope, ...subsidiaryWrite],
  },
  {
    code: "CFO",
    name: "Chief Financial Officer (Subsidiary)",
    level: "subsidiary",
    description: "Subsidiary financial management and budget approvals.",
    permissions: [
      ...subsidiaryScope,
      ...subsidiaryWrite,
      "finance:update:subsidiary",
      "approval:approve:subsidiary",
    ],
  },
  {
    code: "COO",
    name: "Chief Operating Officer (Subsidiary)",
    level: "subsidiary",
    description: "Subsidiary operations, projects and delivery.",
    permissions: [...subsidiaryScope, ...subsidiaryWrite],
  },
  {
    code: "DEPARTMENT_HEAD",
    name: "Department Head",
    level: "department",
    description: "Leads a department: team, KPIs, projects, tasks, approvals.",
    permissions: [...departmentScope, ...departmentWrite, "people:read:department"],
  },
  {
    code: "MANAGER",
    name: "Manager",
    level: "department",
    description: "Manages a team within a department.",
    permissions: [...departmentScope, ...departmentWrite],
  },
  {
    code: "EMPLOYEE",
    name: "Employee",
    level: "department",
    description: "Personal workspace: My Ascendium — tasks, meetings, learning, messages.",
    permissions: [...employeeScope, ...employeeWrite],
  },
  {
    code: "SYSTEM_ADMINISTRATOR",
    name: "System Administrator",
    level: "system",
    description: "Platform administration: users, roles, configuration, integrations.",
    permissions: [
      "admin:administer:group",
      "admin:read:group",
      "admin:update:group",
      "people:read:group",
      "people:update:group",
      "audit:read:group",
      "workflow:read:group",
      "workflow:update:group",
      "notification:read:own",
      "ai:read:group",
    ],
    isSystem: true,
  },
  {
    code: "SECURITY_ADMINISTRATOR",
    name: "Security Administrator",
    level: "system",
    description: "Security operations: sessions, login events, security audit trail.",
    permissions: [
      "admin:read:group",
      "audit:read:group",
      "incident:read:group",
      "incident:update:group",
      "people:read:group",
      "notification:read:own",
    ],
    isSystem: true,
  },
  {
    code: "DATA_ADMINISTRATOR",
    name: "Data Administrator",
    level: "system",
    description: "Data stewardship: reference data, documents, knowledge base curation.",
    permissions: [
      "admin:read:group",
      "document:read:group",
      "document:update:group",
      "document:approve:group",
      "knowledge:read:group",
      "knowledge:update:group",
      "kpi:read:group",
      "notification:read:own",
    ],
    isSystem: true,
  },
];
